---
clickhouse_version: "22.4.4.7"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
clickhouse_packages_st:
  - clickhouse-common-static
clickhouse_database_name: logs
clickhouse_create_table: