---
clickhouse:
  hosts:
    c8-clickhouse:
      ansible_host: 51.250.71.154
      ansible_user: ansible
lighthouse:
  hosts:
    c8-lighthouse:
      ansible_host: 51.250.89.229
      ansible_user: ansible
vector:
  hosts:
    c8-vector:
      ansible_host: 51.250.87.182
      ansible_user: ansible
